### PR TITLE
add a step in readme for local testing

### PR DESCRIPTION
**Pull request by samirsalem**
Readme file missed a step graph codegen

### CODE REVIEW

**Comment by samirsalem** [comment]
@shreyaspapi just added a missing step in readme for local testing of subgraph, could you please merge this?

**Comment by samirsalem** [comment]
Hey @MrSquiggles13  could you please approve and merge this ? (it is just a change in readme file)

**Comment by MrSquiggles13** [comment]
@samirsalem sure sorry i just saw this

**Review by MrSquiggles13 — APPROVED** [review]
Looks good to me

**Pull request merged**
